
all: lab7a lab7b lab7c lab7d lab7e lab7f

lab7a: lab7a.c
	gcc -Wall -Wextra lab7a.c -o lab7a

lab7b: lab7b.c
	gcc -Wall -Wextra lab7b.c -o lab7b

lab7c: lab7c.c
	gcc -Wall -Wextra lab7c.c -o lab7c

lab7d: lab7d.c
	gcc -Wall -Wextra lab7d.c -o lab7d

lab7e: lab7e.c
	gcc -Wall -Wextra lab7e.c -o lab7e

lab7f: lab7f.c
	gcc -Wall -Wextra lab7f.c -o lab7f

